In [2]:
from connect4 import board, mcts
import numpy as np
import random

initial_board = np.zeros((6,7))
tree = mcts.MCTSTree(initial_board)

In [5]:
tree.expand_node(1,initial_board)

In [6]:
tree.node_data

array([[-1, -1,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  1],
       [ 0,  1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0],
       [ 1,  1,  0,  0,  0,  0],
       [ 1,  2,  0,  0,  0,  0],
       [ 1,  3,  0,  0,  0,  0],
       [ 1,  4,  0,  0,  0,  0],
       [ 1,  5,  0,  0,  0,  0],
       [ 1,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0

In [12]:
leaf_node, leaf_board = tree.select_leaf(0, initial_board)


1 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]


In [15]:
board.add_move(initial_board, 1, (0, 1))

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])